### ISSUE TITLE
additionalTable

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#13]
Could you do me a favor and add an`additionalTable` somewhere for testing?
I may do it by hand myself now, I will ping you.

**Comment by constantinpape** [comment]
Yeah, I don't have any data for it lying around, probably best if you just produce some random data and add it yourself.

**Comment by tischi** [comment]
I made an `addedTable` branch for this.
I still called the field `tables` and not `additionalTables` for now.

**Comment by constantinpape** [comment]
> I still called the field `tables` and not `additionalTables` for now.

Ok, do you want to keep the name as `tables` in the spec? I don't really mind either way, but `additionalTables` makes it a bit more explicit that the default table is always loaded and that these ones are loaded on top of it.

**Comment by tischi** [comment]
We can rename to `additionalTables`.

**Comment by tischi** [comment]
By the way, do we have somewhere in the spec which columns the additional tables MUST have in order to be merge-able?

**Comment by constantinpape** [comment]
> which columns the additional tables MUST have in order to be merge-able?

Yes, the segmentation tables need to have `label_id`, the region tables `region_id` and the spot tables will need `spot_id`.

**Comment by tischi** [comment]
Agreed for regions and spot, however for the segmentation, I think we sometimes may also need `image_id` and `timepoint`, because I think we allow for the same label_id across different `timepoint`s.

**Comment by constantinpape** [comment]
> however for the segmentation, I think we sometimes may also need `image_id` and `timepoint`, because I think we allow for the same label_id across different `timepoint`s.

Yea, that makes sense. I guess it depends on whether the default table has these columns; if it does then we also need to have it in the additional tables, right?

**Comment by tischi** [comment]
>  if it does then we also need to have it in the additional tables, right?

yes, otherwise one cannot merge them (if they have not exactly the same number of rows and row order, which is something that we do not require).

**Comment by constantinpape** [comment]
Hey @tischi,
I have been going over this again while adapting the python library to the new spec and I don't think that we ever have `image_id` as a column in the underlying table (i.e. the table that is saved as .tsv). I rather think that this is something that you have previously added to the table when it's loaded (because this information is always present because you know the source name when loading the table and `image_id` is just the source name). I am not sure how things have changed on your end while implementing MoBIE 3, but I think we should keep this as it is (i.e. not adding this as a column to the .tsv). 

This  means the only columns that need to be in additional tables are `label_id/region_id/spot_id` (always) and `timepoint` (if it's in the default table).

**Comment by tischi** [comment]
Yes, I think this is correct. 

However, the UUID for a segment contains the `image_id`.

This is inferred from the name of the segmentation source that contains the additional table.

**Comment by constantinpape** [comment]
> However, the UUID for a segment contains the `image_id`.
> This is inferred from the name of the segmentation source that contains the additional table.

Yep, that makes sense and I agree that you need to check for it when merging the table in your code. But if this fails it's because something went wrong internally and not because of an issue with the underlying table saved on disc. (Whereas if something goes wrong with merging based on `label_id/region_id/spot_id` or `timepoint` it could be due to an issue in the underlying table.)

**Comment by tischi** [comment]
@constantinpape do you think this is still relevant?
if so, would you mind moving it to mobie-viewer-fiji? It is a bit hard for me to keep track of issues in the other repos.

**Comment by constantinpape** [comment]
I think most of this is solved or was migrated to other issues. I will close it.
