### ISSUE TITLE
Grid view center at origin

### ISSUE THREAD

**Issue by tischi** [mobie/spatial-transcriptomics-example-project#24]
```
new MoBIE( "https://github.com/mobie/spatial-transcriptomics-example-project", MoBIESettings.settings().dataset( "pos42" ).gitProjectBranch( "main" ).view( "grid-view" ) );
```

I think here the sources are centered at their origin. This is a bit weird as it leads to negative coordinates:

See for example here:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/2157566/196381862-c1dc9a6a-38ef-48a7-9e2e-f9abd1bb00aa.png">

Not sure we want to do anything about this?

**Comment by constantinpape** [comment]
I guess this is because you set `centerAtOrigin` to true for the transformed grid (https://github.com/mobie/spatial-transcriptomics-example-project/blob/main/data/pos42/dataset.json#L214-L228).

I think that's probably a general behavior of the transformed grid. I am not sure if we need to fix it, since the cooridinates in the grid are somewhat arbitrary in any case.
